version: '3.8'

services:
  go-notik:
    restart: always
    build: ./
    command: ./wait-for-postgres.sh db ./go-notik
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - DB_PASSWORD=password
      - psql_url=postgresql://postgres:password@db:5432/postgres?sslmode=disable
      - GIN_MODE=release

  db:
    restart: always
    image: postgres:latest
    volumes:
    - ././database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
    
  migrate:
    image: migrate/migrate

    depends_on:
      - db

    volumes:
      - D:\!vscode-go-projs\go-notik\:/schema
    # here instead of localhost as the host we use databaseservicename as that is the name we gave to the postgres service
    command:
      [ "-path", "/schema", "-database",  "postgresql://postgres:password@db:5432/postgres?sslmode=disable", "up" ]

volumes:
  pgdata: