name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: make

    - name: Run build
      run: make build

    - name: Run go app
      run: make run
    
    - name: Build docker
      run: make build-docker
